### ISSUE TITLE
Retrieve file location on S3 server after upload

### ISSUE THREAD

**Issue by mebibou** [OriginalEXE/Multer-Storage-S3#1]
Using your example:

```
app.post( '/upload', uploadMiddleware.single( 'attachment' ), function( req, res, next ) {

    res.send( 'File was uploaded succsessfully!' );

});
```

How can I access the `file.Location` within the `post`? could you maybe add a `location: data.Location` at [line 101](https://github.com/OriginalEXE/Multer-Storage-S3/blob/master/index.js#L101)

**Comment by OriginalEXE** [comment]
Hi,

you can access the details of the uploaded file through req.file

Here is an example content of req.file:

```
{
    fieldname: 'attachment',
    originalname: 'my-cool-image.jpg',
    encoding: '7bit',
    mimetype: 'image/jpeg',
    destination: 'attachments/3877b518-0691-4c99-83be-9bd188669dbe',
    filename: '3877b518-06911444070641364.jpg',
    path: 'attachments/3877b518-0691-4c99-83be-9bd188669dbe/3877b518-06911444070641364.jpg',
    size: 24346
}
```

**Comment by mebibou** [comment]
yes but I am asking for the `Location` returned by aws, which is the path on the bucket, something that looks like `https://<bucket>.s3-<region>.amazonaws.com/...`

**Comment by OriginalEXE** [comment]
Hi,

thank you for the suggestion, I have now added both ETag and Location to the callback, under the s3 key.

So to access the location, just use the `req.file.s3.Location`.

Updated the npm package to 1.0.2
