### ISSUE TITLE
How to save file to public folder in s3?

### ISSUE THREAD

**Issue by vlradovanovic** [OriginalEXE/Multer-Storage-S3#5]
Can I store files in 'public' folder of my s3 bucket?
Via settings that you wrote my files are stored in root od a bucket.
(https://s3://[BUCKEET-NAME]).s3.amazonaws.com), but I want my files to be stored on 
(https://s3://[BUCKEET-NAME]).s3.amazonaws.com/public/)...

**Comment by OriginalEXE** [comment]
Hi,

when instantiating the storage, you can pass to it a destination, like so:

```
const s3 = require( 'multer-storage-s3' );
const storage = s3({
  destination : ( req, file, cb ) => { cb( 'public' ); }
});
```

I believe that should work.
